### ISSUE TITLE
编译不成功

### ISSUE THREAD

**Issue by babyfenei** [dzxx36gyy/nali-ipip#3]
![image](https://user-images.githubusercontent.com/22876759/49742472-943b1880-fcd3-11e8-8fb1-1cbebb709445.png)

**Comment by babyfenei** [comment]
另外，请问你们的程序是否支持系统语言环境LANG=C.UTF-8

**Comment by dzxx36gyy** [comment]
LANG=C.UTF-8 IPIP的库默认就支持吧，这个新版gcc的兼容问题刚才合并下了下应该没问题了。。。
