### ISSUE TITLE
无法下载17monipdb.datx

### ISSUE THREAD

**Issue by trytrytogo** [dzxx36gyy/nali-ipip#5]
目前使用centos7
升级IP数据库，执行后的结果。
[root@localhost nali-ipip]# nali-update
Updating /usr/local/share/17monipdb.datx
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   586    0   586    0     0     99      0 --:--:--  0:00:05 --:--:--   134
Successfully Updated
[root@localhost nali-ipip]# ping 114.114.114.114 | nali
PING 114.114.114.114 [] (114.114.114.114 []) 56(84) bytes of data.
64 bytes from 114.114.114.114 []: icmp_seq=1 ttl=84 time=42.3 ms
64 bytes from 114.114.114.114 []: icmp_seq=2 ttl=66 time=42.1 ms
64 bytes from 114.114.114.114 []: icmp_seq=3 ttl=81 time=42.0 ms

**Comment by greensea** [comment]
同样遇到此问题

**Comment by trytrytogo** [comment]
> 同样遇到此问题

看了下，好像是17取消了这个格式的文件还是什么了。

**Comment by trytrytogo** [comment]
已使用其它
